title: Joseph Sawyer
email: joseph@jcsawyer.com
description: "Joseph Sawyer's personal website."
url: "https://jcsawyer.com/"
twitter_username: JosephSawyer
github_username:  jcsawyer

collections:
  - projects

# Defaults set by GitHub, only need for local serving
# https://help.github.com/articles/configuring-jekyll/
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true