title: Joseph Sawyer
email: joseph@jcsawyer.com
description: "Joseph Sawyer's personal website."
url: "https://jcsawyer.com/"
twitter_username: JosephSawyer
github_username:  jcsawyer

collections:
  - projects

gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - .vscode/
  - .github/

# Produces a cleaner folder structure when using categories
permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  offset: 0
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: "posts"

# Defaults set by GitHub, only need for local serving
# https://help.github.com/articles/configuring-jekyll/
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true